# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 17:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=140)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=500)),
                ('picture', models.ImageField(upload_to='uploads/')),
                ('location', models.CharField(choices=[('D', 'Durham'), ('R', 'Raleigh'), ('CH', 'Chapel Hill'), ('C', 'Carrboro'), ('H', 'Hillsboro'), ('M', 'Morrisville')], default='D', max_length=20)),
                ('condition', models.CharField(choices=[('N', 'New'), ('G', 'Good condition'), ('F', 'Fair condition')], default='N', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('D', 'Durham'), ('R', 'Raleigh'), ('CH', 'Chapel Hill'), ('C', 'Carrboro'), ('H', 'Hillsboro'), ('M', 'Morrisville')], default='D', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
