# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='department',
            field=models.CharField(default=None, max_length=35),
        ),
    ]
