# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl', '0002_ad_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='location',
            field=models.CharField(blank=True, choices=[('D', 'Durham'), ('R', 'Raleigh'), ('CH', 'Chapel Hill'), ('C', 'Carrboro'), ('H', 'Hillsboro'), ('M', 'Morrisville')], max_length=20),
        ),
    ]
