# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl', '0004_auto_20161226_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='picture',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
